apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/auth-depl.yaml
      - ./infra/k8s/auth-mongo-depl.yaml
      - ./infra/k8s/ingress-srv.yaml
      - ./infra/k8s/client-depl.yaml
build:
  local:
    push: false
  artifacts:
    - image: shivamkrishna/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: shivamkrishna/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
